// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals

#include "verilated_vcd_c.h"
#include "Vsingle_block_bench__Syms.h"


VL_ATTR_COLD void Vsingle_block_bench___024root__trace_init_sub__TOP__0(Vsingle_block_bench___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsingle_block_bench___024root__trace_init_sub__TOP__0\n"); );
    Vsingle_block_bench__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    const int c = vlSymsp->__Vm_baseCode;
    tracep->pushPrefix("single_block_bench", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+455,0,"N",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+456,0,"ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+457,0,"STOP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+452,0,"clk",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+453,0,"rst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+32,0,"count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+33,0,"start_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+34,0,"start_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+35,0,"is_column",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("arr", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+0+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("arr_out", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+458+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+36,0,"mem_write_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+37,0,"mem_write_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+38,0,"ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+490,0,"valid_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+491,0,"ready_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"we",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+40,0,"mem_read_addr_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+41,0,"mem_read_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+42,0,"writing",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"reading",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("DUT", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+37,0,"mem_write_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+36,0,"mem_write_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+40,0,"mem_read_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+39,0,"we",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+38,0,"ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"reading",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"writing",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+41,0,"mem_read_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+492,0,"request",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+452,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+453,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+455,0,"N",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+44,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+45,0,"prev_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+46,0,"done_rows",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+47,0,"done_all_writes",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"compute_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+49,0,"write_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"start_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+51,0,"write_ready_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+52,0,"write_ready_pos_edge",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+53,0,"arr_write_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+43,0,"read_lock",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"write_lock",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"read_request",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"write_request",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("arr", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+56+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBit(c+88,0,"read_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+89,0,"read_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+90,0,"start_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+91,0,"arr_read_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+92,0,"neg_edge_start_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+93,0,"start_read_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+94,0,"compute_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"start_compute",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("tf_out_arr", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+96+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+128,0,"compute_job_id",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+493,0,"ROWSHIFT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+494,0,"COLSHIFT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("arr_to_write", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+129+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+161,0,"job_id_prev",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("inv_dct", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+495,0,"N",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->pushPrefix("out", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+162+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBit(c+94,0,"valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+48,0,"ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+128,0,"job_id_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("in_array", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+194+i*1,0,"",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+226,0,"job_id_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+95,0,"start_compute",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+452,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+454,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+128,0,"job_id",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+94,0,"valid_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+496,0,"n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->pushPrefix("t_array", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+227+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+259,0,"state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->pushPrefix("T", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+260+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk11", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk12", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+292,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk13", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk14", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk15", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+293,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk16", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk17", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+294,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk18", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk19", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+295,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk20", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk21", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+296,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk22", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk23", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk24", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+297,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk25", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk26", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+298,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk27", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+299,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk28", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk29", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk30", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+300,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk3", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk4", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+301,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk31", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk32", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+302,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk33", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk34", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+303,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk35", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk36", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+304,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk37", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk38", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk39", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+305,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk40", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk41", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+306,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk42", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk43", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+307,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk44", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk45", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+308,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk5", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk6", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+309,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk7", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk8", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+310,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("unnamedblk9", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->pushPrefix("unnamedblk10", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+311,0,"b_res",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("lock_mgr", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+43,0,"read_lock",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"write_lock",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"read_request",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"write_request",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+452,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+453,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+312,0,"read_last",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"read_lock_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"write_lock_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("reader", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+495,0,"N",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+497,0,"ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->pushPrefix("array", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+313+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+40,0,"mem_read_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+88,0,"valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+89,0,"ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"mem_lock_request",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+41,0,"mem_read_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+345,0,"start_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+90,0,"start_read",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+46,0,"is_column",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"mem_lock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+452,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+454,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("arr_internal", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+346+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+378,0,"arr_reg_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declQuad(c+379,0,"state_mem_read",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 32,0);
    tracep->declBit(c+381,0,"try_get_lock",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"mem_lock_request_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+40,0,"mem_read_addr_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+89,0,"ready_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+88,0,"valid_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("writer", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+495,0,"N",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+36,0,"mem_write_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+37,0,"mem_write_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+49,0,"ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+39,0,"we",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"mem_lock_request",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("arr", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+382+i*1,0,"",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+414,0,"start_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+42,0,"mem_lock",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+50,0,"start_write",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+46,0,"is_column",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+452,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+454,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+415,0,"j",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->pushPrefix("arr_internal", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+416+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+448,0,"state_mem_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+36,0,"mem_write_addr_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+449,0,"mem_write_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+49,0,"ready_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+450,0,"try_get_lock",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"mem_lock_req_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("TESTMEM_16_1024", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+41,0,"q",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+37,0,"d",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+36,0,"write_address",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBus(c+40,0,"read_address",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+39,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+453,0,"rst",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+452,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+451,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vsingle_block_bench___024root__trace_init_top(Vsingle_block_bench___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsingle_block_bench___024root__trace_init_top\n"); );
    Vsingle_block_bench__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vsingle_block_bench___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vsingle_block_bench___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vsingle_block_bench___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vsingle_block_bench___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vsingle_block_bench___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vsingle_block_bench___024root__trace_register(Vsingle_block_bench___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsingle_block_bench___024root__trace_register\n"); );
    Vsingle_block_bench__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vsingle_block_bench___024root__trace_const_0, 0, vlSelf);
    tracep->addFullCb(&Vsingle_block_bench___024root__trace_full_0, 0, vlSelf);
    tracep->addChgCb(&Vsingle_block_bench___024root__trace_chg_0, 0, vlSelf);
    tracep->addCleanupCb(&Vsingle_block_bench___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vsingle_block_bench___024root__trace_const_0_sub_0(Vsingle_block_bench___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vsingle_block_bench___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsingle_block_bench___024root__trace_const_0\n"); );
    // Body
    Vsingle_block_bench___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vsingle_block_bench___024root*>(voidSelf);
    Vsingle_block_bench__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vsingle_block_bench___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vsingle_block_bench___024root__trace_const_0_sub_0(Vsingle_block_bench___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsingle_block_bench___024root__trace_const_0_sub_0\n"); );
    Vsingle_block_bench__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullIData(oldp+455,(0x00000020U),32);
    bufp->fullIData(oldp+456,(0x0000000aU),32);
    bufp->fullIData(oldp+457,(0x00001770U),32);
    bufp->fullSData(oldp+458,(vlSelfRef.single_block_bench__DOT__arr_out[0]),16);
    bufp->fullSData(oldp+459,(vlSelfRef.single_block_bench__DOT__arr_out[1]),16);
    bufp->fullSData(oldp+460,(vlSelfRef.single_block_bench__DOT__arr_out[2]),16);
    bufp->fullSData(oldp+461,(vlSelfRef.single_block_bench__DOT__arr_out[3]),16);
    bufp->fullSData(oldp+462,(vlSelfRef.single_block_bench__DOT__arr_out[4]),16);
    bufp->fullSData(oldp+463,(vlSelfRef.single_block_bench__DOT__arr_out[5]),16);
    bufp->fullSData(oldp+464,(vlSelfRef.single_block_bench__DOT__arr_out[6]),16);
    bufp->fullSData(oldp+465,(vlSelfRef.single_block_bench__DOT__arr_out[7]),16);
    bufp->fullSData(oldp+466,(vlSelfRef.single_block_bench__DOT__arr_out[8]),16);
    bufp->fullSData(oldp+467,(vlSelfRef.single_block_bench__DOT__arr_out[9]),16);
    bufp->fullSData(oldp+468,(vlSelfRef.single_block_bench__DOT__arr_out[10]),16);
    bufp->fullSData(oldp+469,(vlSelfRef.single_block_bench__DOT__arr_out[11]),16);
    bufp->fullSData(oldp+470,(vlSelfRef.single_block_bench__DOT__arr_out[12]),16);
    bufp->fullSData(oldp+471,(vlSelfRef.single_block_bench__DOT__arr_out[13]),16);
    bufp->fullSData(oldp+472,(vlSelfRef.single_block_bench__DOT__arr_out[14]),16);
    bufp->fullSData(oldp+473,(vlSelfRef.single_block_bench__DOT__arr_out[15]),16);
    bufp->fullSData(oldp+474,(vlSelfRef.single_block_bench__DOT__arr_out[16]),16);
    bufp->fullSData(oldp+475,(vlSelfRef.single_block_bench__DOT__arr_out[17]),16);
    bufp->fullSData(oldp+476,(vlSelfRef.single_block_bench__DOT__arr_out[18]),16);
    bufp->fullSData(oldp+477,(vlSelfRef.single_block_bench__DOT__arr_out[19]),16);
    bufp->fullSData(oldp+478,(vlSelfRef.single_block_bench__DOT__arr_out[20]),16);
    bufp->fullSData(oldp+479,(vlSelfRef.single_block_bench__DOT__arr_out[21]),16);
    bufp->fullSData(oldp+480,(vlSelfRef.single_block_bench__DOT__arr_out[22]),16);
    bufp->fullSData(oldp+481,(vlSelfRef.single_block_bench__DOT__arr_out[23]),16);
    bufp->fullSData(oldp+482,(vlSelfRef.single_block_bench__DOT__arr_out[24]),16);
    bufp->fullSData(oldp+483,(vlSelfRef.single_block_bench__DOT__arr_out[25]),16);
    bufp->fullSData(oldp+484,(vlSelfRef.single_block_bench__DOT__arr_out[26]),16);
    bufp->fullSData(oldp+485,(vlSelfRef.single_block_bench__DOT__arr_out[27]),16);
    bufp->fullSData(oldp+486,(vlSelfRef.single_block_bench__DOT__arr_out[28]),16);
    bufp->fullSData(oldp+487,(vlSelfRef.single_block_bench__DOT__arr_out[29]),16);
    bufp->fullSData(oldp+488,(vlSelfRef.single_block_bench__DOT__arr_out[30]),16);
    bufp->fullSData(oldp+489,(vlSelfRef.single_block_bench__DOT__arr_out[31]),16);
    bufp->fullBit(oldp+490,(vlSelfRef.single_block_bench__DOT__valid_out));
    bufp->fullBit(oldp+491,(vlSelfRef.single_block_bench__DOT__ready_out));
    bufp->fullBit(oldp+492,(1U));
    bufp->fullIData(oldp+493,(2U),32);
    bufp->fullIData(oldp+494,(4U),32);
    bufp->fullIData(oldp+495,(0x00000020U),32);
    bufp->fullIData(oldp+496,(5U),32);
    bufp->fullIData(oldp+497,(0x0000000aU),32);
}

VL_ATTR_COLD void Vsingle_block_bench___024root__trace_full_0_sub_0(Vsingle_block_bench___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vsingle_block_bench___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsingle_block_bench___024root__trace_full_0\n"); );
    // Body
    Vsingle_block_bench___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vsingle_block_bench___024root*>(voidSelf);
    Vsingle_block_bench__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vsingle_block_bench___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vsingle_block_bench___024root__trace_full_0_sub_0(Vsingle_block_bench___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsingle_block_bench___024root__trace_full_0_sub_0\n"); );
    Vsingle_block_bench__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullSData(oldp+0,(vlSelfRef.single_block_bench__DOT__arr[0]),16);
    bufp->fullSData(oldp+1,(vlSelfRef.single_block_bench__DOT__arr[1]),16);
    bufp->fullSData(oldp+2,(vlSelfRef.single_block_bench__DOT__arr[2]),16);
    bufp->fullSData(oldp+3,(vlSelfRef.single_block_bench__DOT__arr[3]),16);
    bufp->fullSData(oldp+4,(vlSelfRef.single_block_bench__DOT__arr[4]),16);
    bufp->fullSData(oldp+5,(vlSelfRef.single_block_bench__DOT__arr[5]),16);
    bufp->fullSData(oldp+6,(vlSelfRef.single_block_bench__DOT__arr[6]),16);
    bufp->fullSData(oldp+7,(vlSelfRef.single_block_bench__DOT__arr[7]),16);
    bufp->fullSData(oldp+8,(vlSelfRef.single_block_bench__DOT__arr[8]),16);
    bufp->fullSData(oldp+9,(vlSelfRef.single_block_bench__DOT__arr[9]),16);
    bufp->fullSData(oldp+10,(vlSelfRef.single_block_bench__DOT__arr[10]),16);
    bufp->fullSData(oldp+11,(vlSelfRef.single_block_bench__DOT__arr[11]),16);
    bufp->fullSData(oldp+12,(vlSelfRef.single_block_bench__DOT__arr[12]),16);
    bufp->fullSData(oldp+13,(vlSelfRef.single_block_bench__DOT__arr[13]),16);
    bufp->fullSData(oldp+14,(vlSelfRef.single_block_bench__DOT__arr[14]),16);
    bufp->fullSData(oldp+15,(vlSelfRef.single_block_bench__DOT__arr[15]),16);
    bufp->fullSData(oldp+16,(vlSelfRef.single_block_bench__DOT__arr[16]),16);
    bufp->fullSData(oldp+17,(vlSelfRef.single_block_bench__DOT__arr[17]),16);
    bufp->fullSData(oldp+18,(vlSelfRef.single_block_bench__DOT__arr[18]),16);
    bufp->fullSData(oldp+19,(vlSelfRef.single_block_bench__DOT__arr[19]),16);
    bufp->fullSData(oldp+20,(vlSelfRef.single_block_bench__DOT__arr[20]),16);
    bufp->fullSData(oldp+21,(vlSelfRef.single_block_bench__DOT__arr[21]),16);
    bufp->fullSData(oldp+22,(vlSelfRef.single_block_bench__DOT__arr[22]),16);
    bufp->fullSData(oldp+23,(vlSelfRef.single_block_bench__DOT__arr[23]),16);
    bufp->fullSData(oldp+24,(vlSelfRef.single_block_bench__DOT__arr[24]),16);
    bufp->fullSData(oldp+25,(vlSelfRef.single_block_bench__DOT__arr[25]),16);
    bufp->fullSData(oldp+26,(vlSelfRef.single_block_bench__DOT__arr[26]),16);
    bufp->fullSData(oldp+27,(vlSelfRef.single_block_bench__DOT__arr[27]),16);
    bufp->fullSData(oldp+28,(vlSelfRef.single_block_bench__DOT__arr[28]),16);
    bufp->fullSData(oldp+29,(vlSelfRef.single_block_bench__DOT__arr[29]),16);
    bufp->fullSData(oldp+30,(vlSelfRef.single_block_bench__DOT__arr[30]),16);
    bufp->fullSData(oldp+31,(vlSelfRef.single_block_bench__DOT__arr[31]),16);
    bufp->fullIData(oldp+32,(vlSelfRef.single_block_bench__DOT__count),32);
    bufp->fullSData(oldp+33,(vlSelfRef.single_block_bench__DOT__start_addr),10);
    bufp->fullBit(oldp+34,(vlSelfRef.single_block_bench__DOT__start_write));
    bufp->fullBit(oldp+35,(vlSelfRef.single_block_bench__DOT__is_column));
    bufp->fullSData(oldp+36,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__mem_write_addr_reg),10);
    bufp->fullSData(oldp+37,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal
                             [vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__mem_write_counter]),16);
    bufp->fullBit(oldp+38,((0U == (IData)(vlSelfRef.single_block_bench__DOT__DUT__DOT__state))));
    bufp->fullBit(oldp+39,((0U != vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__state_mem_write)));
    bufp->fullSData(oldp+40,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__mem_read_addr_reg),10);
    bufp->fullSData(oldp+41,(vlSelfRef.single_block_bench__DOT__mem_read_q),16);
    bufp->fullBit(oldp+42,(vlSelfRef.single_block_bench__DOT__DUT__DOT__lock_mgr__DOT__write_lock_reg));
    bufp->fullBit(oldp+43,(vlSelfRef.single_block_bench__DOT__DUT__DOT__lock_mgr__DOT__read_lock_reg));
    bufp->fullCData(oldp+44,(vlSelfRef.single_block_bench__DOT__DUT__DOT__state),2);
    bufp->fullCData(oldp+45,(vlSelfRef.single_block_bench__DOT__DUT__DOT__prev_state),2);
    bufp->fullBit(oldp+46,(vlSelfRef.single_block_bench__DOT__DUT__DOT__done_rows));
    bufp->fullBit(oldp+47,(((0x1fU == (IData)(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_write_counter)) 
                            & (IData)(vlSelfRef.single_block_bench__DOT__DUT__DOT__write_ready_pos_edge))));
    bufp->fullBit(oldp+48,((0U == (IData)(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__state))));
    bufp->fullBit(oldp+49,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__ready_reg));
    bufp->fullBit(oldp+50,(vlSelfRef.single_block_bench__DOT__DUT__DOT__start_write));
    bufp->fullBit(oldp+51,(vlSelfRef.single_block_bench__DOT__DUT__DOT__write_ready_prev));
    bufp->fullBit(oldp+52,(vlSelfRef.single_block_bench__DOT__DUT__DOT__write_ready_pos_edge));
    bufp->fullCData(oldp+53,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_write_counter),5);
    bufp->fullBit(oldp+54,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__mem_lock_request_reg));
    bufp->fullBit(oldp+55,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__mem_lock_req_reg));
    bufp->fullSData(oldp+56,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[0]),16);
    bufp->fullSData(oldp+57,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[1]),16);
    bufp->fullSData(oldp+58,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[2]),16);
    bufp->fullSData(oldp+59,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[3]),16);
    bufp->fullSData(oldp+60,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[4]),16);
    bufp->fullSData(oldp+61,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[5]),16);
    bufp->fullSData(oldp+62,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[6]),16);
    bufp->fullSData(oldp+63,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[7]),16);
    bufp->fullSData(oldp+64,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[8]),16);
    bufp->fullSData(oldp+65,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[9]),16);
    bufp->fullSData(oldp+66,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[10]),16);
    bufp->fullSData(oldp+67,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[11]),16);
    bufp->fullSData(oldp+68,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[12]),16);
    bufp->fullSData(oldp+69,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[13]),16);
    bufp->fullSData(oldp+70,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[14]),16);
    bufp->fullSData(oldp+71,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[15]),16);
    bufp->fullSData(oldp+72,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[16]),16);
    bufp->fullSData(oldp+73,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[17]),16);
    bufp->fullSData(oldp+74,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[18]),16);
    bufp->fullSData(oldp+75,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[19]),16);
    bufp->fullSData(oldp+76,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[20]),16);
    bufp->fullSData(oldp+77,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[21]),16);
    bufp->fullSData(oldp+78,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[22]),16);
    bufp->fullSData(oldp+79,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[23]),16);
    bufp->fullSData(oldp+80,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[24]),16);
    bufp->fullSData(oldp+81,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[25]),16);
    bufp->fullSData(oldp+82,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[26]),16);
    bufp->fullSData(oldp+83,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[27]),16);
    bufp->fullSData(oldp+84,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[28]),16);
    bufp->fullSData(oldp+85,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[29]),16);
    bufp->fullSData(oldp+86,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[30]),16);
    bufp->fullSData(oldp+87,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr[31]),16);
    bufp->fullBit(oldp+88,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__valid_reg));
    bufp->fullBit(oldp+89,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__ready_reg));
    bufp->fullBit(oldp+90,(vlSelfRef.single_block_bench__DOT__DUT__DOT__start_read));
    bufp->fullCData(oldp+91,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_read_counter),5);
    bufp->fullBit(oldp+92,(((~ (IData)(vlSelfRef.single_block_bench__DOT__DUT__DOT__start_read)) 
                            & (IData)(vlSelfRef.single_block_bench__DOT__DUT__DOT__start_read_prev))));
    bufp->fullBit(oldp+93,(vlSelfRef.single_block_bench__DOT__DUT__DOT__start_read_prev));
    bufp->fullBit(oldp+94,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__valid_reg));
    bufp->fullBit(oldp+95,(vlSelfRef.single_block_bench__DOT__DUT__DOT__start_compute));
    bufp->fullSData(oldp+96,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[0]),16);
    bufp->fullSData(oldp+97,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[1]),16);
    bufp->fullSData(oldp+98,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[2]),16);
    bufp->fullSData(oldp+99,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[3]),16);
    bufp->fullSData(oldp+100,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[4]),16);
    bufp->fullSData(oldp+101,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[5]),16);
    bufp->fullSData(oldp+102,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[6]),16);
    bufp->fullSData(oldp+103,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[7]),16);
    bufp->fullSData(oldp+104,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[8]),16);
    bufp->fullSData(oldp+105,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[9]),16);
    bufp->fullSData(oldp+106,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[10]),16);
    bufp->fullSData(oldp+107,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[11]),16);
    bufp->fullSData(oldp+108,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[12]),16);
    bufp->fullSData(oldp+109,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[13]),16);
    bufp->fullSData(oldp+110,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[14]),16);
    bufp->fullSData(oldp+111,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[15]),16);
    bufp->fullSData(oldp+112,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[16]),16);
    bufp->fullSData(oldp+113,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[17]),16);
    bufp->fullSData(oldp+114,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[18]),16);
    bufp->fullSData(oldp+115,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[19]),16);
    bufp->fullSData(oldp+116,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[20]),16);
    bufp->fullSData(oldp+117,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[21]),16);
    bufp->fullSData(oldp+118,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[22]),16);
    bufp->fullSData(oldp+119,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[23]),16);
    bufp->fullSData(oldp+120,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[24]),16);
    bufp->fullSData(oldp+121,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[25]),16);
    bufp->fullSData(oldp+122,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[26]),16);
    bufp->fullSData(oldp+123,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[27]),16);
    bufp->fullSData(oldp+124,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[28]),16);
    bufp->fullSData(oldp+125,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[29]),16);
    bufp->fullSData(oldp+126,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[30]),16);
    bufp->fullSData(oldp+127,(vlSelfRef.single_block_bench__DOT__DUT__DOT__tf_out_arr[31]),16);
    bufp->fullSData(oldp+128,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__job_id),16);
    bufp->fullSData(oldp+129,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[0]),16);
    bufp->fullSData(oldp+130,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[1]),16);
    bufp->fullSData(oldp+131,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[2]),16);
    bufp->fullSData(oldp+132,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[3]),16);
    bufp->fullSData(oldp+133,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[4]),16);
    bufp->fullSData(oldp+134,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[5]),16);
    bufp->fullSData(oldp+135,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[6]),16);
    bufp->fullSData(oldp+136,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[7]),16);
    bufp->fullSData(oldp+137,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[8]),16);
    bufp->fullSData(oldp+138,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[9]),16);
    bufp->fullSData(oldp+139,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[10]),16);
    bufp->fullSData(oldp+140,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[11]),16);
    bufp->fullSData(oldp+141,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[12]),16);
    bufp->fullSData(oldp+142,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[13]),16);
    bufp->fullSData(oldp+143,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[14]),16);
    bufp->fullSData(oldp+144,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[15]),16);
    bufp->fullSData(oldp+145,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[16]),16);
    bufp->fullSData(oldp+146,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[17]),16);
    bufp->fullSData(oldp+147,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[18]),16);
    bufp->fullSData(oldp+148,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[19]),16);
    bufp->fullSData(oldp+149,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[20]),16);
    bufp->fullSData(oldp+150,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[21]),16);
    bufp->fullSData(oldp+151,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[22]),16);
    bufp->fullSData(oldp+152,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[23]),16);
    bufp->fullSData(oldp+153,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[24]),16);
    bufp->fullSData(oldp+154,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[25]),16);
    bufp->fullSData(oldp+155,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[26]),16);
    bufp->fullSData(oldp+156,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[27]),16);
    bufp->fullSData(oldp+157,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[28]),16);
    bufp->fullSData(oldp+158,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[29]),16);
    bufp->fullSData(oldp+159,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[30]),16);
    bufp->fullSData(oldp+160,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_to_write[31]),16);
    bufp->fullSData(oldp+161,(vlSelfRef.single_block_bench__DOT__DUT__DOT__job_id_prev),16);
    bufp->fullSData(oldp+162,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[0]),16);
    bufp->fullSData(oldp+163,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[1]),16);
    bufp->fullSData(oldp+164,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[2]),16);
    bufp->fullSData(oldp+165,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[3]),16);
    bufp->fullSData(oldp+166,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[4]),16);
    bufp->fullSData(oldp+167,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[5]),16);
    bufp->fullSData(oldp+168,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[6]),16);
    bufp->fullSData(oldp+169,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[7]),16);
    bufp->fullSData(oldp+170,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[8]),16);
    bufp->fullSData(oldp+171,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[9]),16);
    bufp->fullSData(oldp+172,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[10]),16);
    bufp->fullSData(oldp+173,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[11]),16);
    bufp->fullSData(oldp+174,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[12]),16);
    bufp->fullSData(oldp+175,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[13]),16);
    bufp->fullSData(oldp+176,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[14]),16);
    bufp->fullSData(oldp+177,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[15]),16);
    bufp->fullSData(oldp+178,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[16]),16);
    bufp->fullSData(oldp+179,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[17]),16);
    bufp->fullSData(oldp+180,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[18]),16);
    bufp->fullSData(oldp+181,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[19]),16);
    bufp->fullSData(oldp+182,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[20]),16);
    bufp->fullSData(oldp+183,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[21]),16);
    bufp->fullSData(oldp+184,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[22]),16);
    bufp->fullSData(oldp+185,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[23]),16);
    bufp->fullSData(oldp+186,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[24]),16);
    bufp->fullSData(oldp+187,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[25]),16);
    bufp->fullSData(oldp+188,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[26]),16);
    bufp->fullSData(oldp+189,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[27]),16);
    bufp->fullSData(oldp+190,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[28]),16);
    bufp->fullSData(oldp+191,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[29]),16);
    bufp->fullSData(oldp+192,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[30]),16);
    bufp->fullSData(oldp+193,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__out[31]),16);
    bufp->fullSData(oldp+194,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[0]),16);
    bufp->fullSData(oldp+195,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[1]),16);
    bufp->fullSData(oldp+196,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[2]),16);
    bufp->fullSData(oldp+197,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[3]),16);
    bufp->fullSData(oldp+198,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[4]),16);
    bufp->fullSData(oldp+199,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[5]),16);
    bufp->fullSData(oldp+200,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[6]),16);
    bufp->fullSData(oldp+201,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[7]),16);
    bufp->fullSData(oldp+202,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[8]),16);
    bufp->fullSData(oldp+203,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[9]),16);
    bufp->fullSData(oldp+204,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[10]),16);
    bufp->fullSData(oldp+205,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[11]),16);
    bufp->fullSData(oldp+206,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[12]),16);
    bufp->fullSData(oldp+207,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[13]),16);
    bufp->fullSData(oldp+208,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[14]),16);
    bufp->fullSData(oldp+209,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[15]),16);
    bufp->fullSData(oldp+210,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[16]),16);
    bufp->fullSData(oldp+211,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[17]),16);
    bufp->fullSData(oldp+212,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[18]),16);
    bufp->fullSData(oldp+213,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[19]),16);
    bufp->fullSData(oldp+214,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[20]),16);
    bufp->fullSData(oldp+215,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[21]),16);
    bufp->fullSData(oldp+216,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[22]),16);
    bufp->fullSData(oldp+217,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[23]),16);
    bufp->fullSData(oldp+218,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[24]),16);
    bufp->fullSData(oldp+219,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[25]),16);
    bufp->fullSData(oldp+220,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[26]),16);
    bufp->fullSData(oldp+221,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[27]),16);
    bufp->fullSData(oldp+222,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[28]),16);
    bufp->fullSData(oldp+223,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[29]),16);
    bufp->fullSData(oldp+224,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[30]),16);
    bufp->fullSData(oldp+225,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__in_array[31]),16);
    bufp->fullSData(oldp+226,(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_read_counter),16);
    bufp->fullSData(oldp+227,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[0]),16);
    bufp->fullSData(oldp+228,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[1]),16);
    bufp->fullSData(oldp+229,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[2]),16);
    bufp->fullSData(oldp+230,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[3]),16);
    bufp->fullSData(oldp+231,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[4]),16);
    bufp->fullSData(oldp+232,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[5]),16);
    bufp->fullSData(oldp+233,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[6]),16);
    bufp->fullSData(oldp+234,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[7]),16);
    bufp->fullSData(oldp+235,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[8]),16);
    bufp->fullSData(oldp+236,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[9]),16);
    bufp->fullSData(oldp+237,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[10]),16);
    bufp->fullSData(oldp+238,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[11]),16);
    bufp->fullSData(oldp+239,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[12]),16);
    bufp->fullSData(oldp+240,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[13]),16);
    bufp->fullSData(oldp+241,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[14]),16);
    bufp->fullSData(oldp+242,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[15]),16);
    bufp->fullSData(oldp+243,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[16]),16);
    bufp->fullSData(oldp+244,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[17]),16);
    bufp->fullSData(oldp+245,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[18]),16);
    bufp->fullSData(oldp+246,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[19]),16);
    bufp->fullSData(oldp+247,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[20]),16);
    bufp->fullSData(oldp+248,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[21]),16);
    bufp->fullSData(oldp+249,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[22]),16);
    bufp->fullSData(oldp+250,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[23]),16);
    bufp->fullSData(oldp+251,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[24]),16);
    bufp->fullSData(oldp+252,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[25]),16);
    bufp->fullSData(oldp+253,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[26]),16);
    bufp->fullSData(oldp+254,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[27]),16);
    bufp->fullSData(oldp+255,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[28]),16);
    bufp->fullSData(oldp+256,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[29]),16);
    bufp->fullSData(oldp+257,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[30]),16);
    bufp->fullSData(oldp+258,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__t_array[31]),16);
    bufp->fullCData(oldp+259,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__state),5);
    bufp->fullSData(oldp+260,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[0]),16);
    bufp->fullSData(oldp+261,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[1]),16);
    bufp->fullSData(oldp+262,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[2]),16);
    bufp->fullSData(oldp+263,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[3]),16);
    bufp->fullSData(oldp+264,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[4]),16);
    bufp->fullSData(oldp+265,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[5]),16);
    bufp->fullSData(oldp+266,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[6]),16);
    bufp->fullSData(oldp+267,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[7]),16);
    bufp->fullSData(oldp+268,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[8]),16);
    bufp->fullSData(oldp+269,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[9]),16);
    bufp->fullSData(oldp+270,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[10]),16);
    bufp->fullSData(oldp+271,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[11]),16);
    bufp->fullSData(oldp+272,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[12]),16);
    bufp->fullSData(oldp+273,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[13]),16);
    bufp->fullSData(oldp+274,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[14]),16);
    bufp->fullSData(oldp+275,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[15]),16);
    bufp->fullSData(oldp+276,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[16]),16);
    bufp->fullSData(oldp+277,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[17]),16);
    bufp->fullSData(oldp+278,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[18]),16);
    bufp->fullSData(oldp+279,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[19]),16);
    bufp->fullSData(oldp+280,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[20]),16);
    bufp->fullSData(oldp+281,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[21]),16);
    bufp->fullSData(oldp+282,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[22]),16);
    bufp->fullSData(oldp+283,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[23]),16);
    bufp->fullSData(oldp+284,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[24]),16);
    bufp->fullSData(oldp+285,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[25]),16);
    bufp->fullSData(oldp+286,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[26]),16);
    bufp->fullSData(oldp+287,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[27]),16);
    bufp->fullSData(oldp+288,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[28]),16);
    bufp->fullSData(oldp+289,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[29]),16);
    bufp->fullSData(oldp+290,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[30]),16);
    bufp->fullSData(oldp+291,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__T[31]),16);
    bufp->fullIData(oldp+292,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk11__DOT__unnamedblk12__DOT__b_res),32);
    bufp->fullIData(oldp+293,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk13__DOT__unnamedblk14__DOT__unnamedblk15__DOT__b_res),32);
    bufp->fullIData(oldp+294,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk16__DOT__unnamedblk17__DOT__b_res),32);
    bufp->fullIData(oldp+295,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk18__DOT__unnamedblk19__DOT__b_res),32);
    bufp->fullIData(oldp+296,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk20__DOT__unnamedblk21__DOT__b_res),32);
    bufp->fullIData(oldp+297,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk22__DOT__unnamedblk23__DOT__unnamedblk24__DOT__b_res),32);
    bufp->fullIData(oldp+298,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk25__DOT__unnamedblk26__DOT__b_res),32);
    bufp->fullIData(oldp+299,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk27__DOT__b_res),32);
    bufp->fullIData(oldp+300,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk28__DOT__unnamedblk29__DOT__unnamedblk30__DOT__b_res),32);
    bufp->fullIData(oldp+301,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk3__DOT__unnamedblk4__DOT__b_res),32);
    bufp->fullIData(oldp+302,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk31__DOT__unnamedblk32__DOT__b_res),32);
    bufp->fullIData(oldp+303,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk33__DOT__unnamedblk34__DOT__b_res),32);
    bufp->fullIData(oldp+304,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk35__DOT__unnamedblk36__DOT__b_res),32);
    bufp->fullIData(oldp+305,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk37__DOT__unnamedblk38__DOT__unnamedblk39__DOT__b_res),32);
    bufp->fullIData(oldp+306,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk40__DOT__unnamedblk41__DOT__b_res),32);
    bufp->fullIData(oldp+307,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk42__DOT__unnamedblk43__DOT__b_res),32);
    bufp->fullIData(oldp+308,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk44__DOT__unnamedblk45__DOT__b_res),32);
    bufp->fullIData(oldp+309,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk5__DOT__unnamedblk6__DOT__b_res),32);
    bufp->fullIData(oldp+310,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk7__DOT__unnamedblk8__DOT__b_res),32);
    bufp->fullIData(oldp+311,(vlSelfRef.single_block_bench__DOT__DUT__DOT__inv_dct__DOT__unnamedblk9__DOT__unnamedblk10__DOT__b_res),32);
    bufp->fullBit(oldp+312,(vlSelfRef.single_block_bench__DOT__DUT__DOT__lock_mgr__DOT__read_last));
    bufp->fullSData(oldp+313,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[0]),16);
    bufp->fullSData(oldp+314,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[1]),16);
    bufp->fullSData(oldp+315,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[2]),16);
    bufp->fullSData(oldp+316,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[3]),16);
    bufp->fullSData(oldp+317,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[4]),16);
    bufp->fullSData(oldp+318,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[5]),16);
    bufp->fullSData(oldp+319,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[6]),16);
    bufp->fullSData(oldp+320,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[7]),16);
    bufp->fullSData(oldp+321,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[8]),16);
    bufp->fullSData(oldp+322,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[9]),16);
    bufp->fullSData(oldp+323,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[10]),16);
    bufp->fullSData(oldp+324,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[11]),16);
    bufp->fullSData(oldp+325,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[12]),16);
    bufp->fullSData(oldp+326,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[13]),16);
    bufp->fullSData(oldp+327,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[14]),16);
    bufp->fullSData(oldp+328,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[15]),16);
    bufp->fullSData(oldp+329,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[16]),16);
    bufp->fullSData(oldp+330,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[17]),16);
    bufp->fullSData(oldp+331,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[18]),16);
    bufp->fullSData(oldp+332,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[19]),16);
    bufp->fullSData(oldp+333,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[20]),16);
    bufp->fullSData(oldp+334,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[21]),16);
    bufp->fullSData(oldp+335,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[22]),16);
    bufp->fullSData(oldp+336,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[23]),16);
    bufp->fullSData(oldp+337,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[24]),16);
    bufp->fullSData(oldp+338,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[25]),16);
    bufp->fullSData(oldp+339,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[26]),16);
    bufp->fullSData(oldp+340,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[27]),16);
    bufp->fullSData(oldp+341,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[28]),16);
    bufp->fullSData(oldp+342,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[29]),16);
    bufp->fullSData(oldp+343,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[30]),16);
    bufp->fullSData(oldp+344,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__array[31]),16);
    bufp->fullSData(oldp+345,(vlSelfRef.single_block_bench__DOT__DUT__DOT____Vcellinp__reader__start_addr),10);
    bufp->fullSData(oldp+346,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[0]),16);
    bufp->fullSData(oldp+347,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[1]),16);
    bufp->fullSData(oldp+348,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[2]),16);
    bufp->fullSData(oldp+349,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[3]),16);
    bufp->fullSData(oldp+350,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[4]),16);
    bufp->fullSData(oldp+351,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[5]),16);
    bufp->fullSData(oldp+352,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[6]),16);
    bufp->fullSData(oldp+353,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[7]),16);
    bufp->fullSData(oldp+354,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[8]),16);
    bufp->fullSData(oldp+355,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[9]),16);
    bufp->fullSData(oldp+356,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[10]),16);
    bufp->fullSData(oldp+357,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[11]),16);
    bufp->fullSData(oldp+358,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[12]),16);
    bufp->fullSData(oldp+359,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[13]),16);
    bufp->fullSData(oldp+360,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[14]),16);
    bufp->fullSData(oldp+361,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[15]),16);
    bufp->fullSData(oldp+362,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[16]),16);
    bufp->fullSData(oldp+363,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[17]),16);
    bufp->fullSData(oldp+364,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[18]),16);
    bufp->fullSData(oldp+365,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[19]),16);
    bufp->fullSData(oldp+366,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[20]),16);
    bufp->fullSData(oldp+367,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[21]),16);
    bufp->fullSData(oldp+368,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[22]),16);
    bufp->fullSData(oldp+369,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[23]),16);
    bufp->fullSData(oldp+370,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[24]),16);
    bufp->fullSData(oldp+371,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[25]),16);
    bufp->fullSData(oldp+372,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[26]),16);
    bufp->fullSData(oldp+373,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[27]),16);
    bufp->fullSData(oldp+374,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[28]),16);
    bufp->fullSData(oldp+375,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[29]),16);
    bufp->fullSData(oldp+376,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[30]),16);
    bufp->fullSData(oldp+377,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__arr_internal[31]),16);
    bufp->fullIData(oldp+378,((IData)((vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__state_mem_read 
                                       >> 1U))),32);
    bufp->fullQData(oldp+379,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__state_mem_read),33);
    bufp->fullBit(oldp+381,(vlSelfRef.single_block_bench__DOT__DUT__DOT__reader__DOT__try_get_lock));
    bufp->fullSData(oldp+382,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[0]),16);
    bufp->fullSData(oldp+383,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[1]),16);
    bufp->fullSData(oldp+384,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[2]),16);
    bufp->fullSData(oldp+385,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[3]),16);
    bufp->fullSData(oldp+386,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[4]),16);
    bufp->fullSData(oldp+387,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[5]),16);
    bufp->fullSData(oldp+388,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[6]),16);
    bufp->fullSData(oldp+389,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[7]),16);
    bufp->fullSData(oldp+390,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[8]),16);
    bufp->fullSData(oldp+391,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[9]),16);
    bufp->fullSData(oldp+392,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[10]),16);
    bufp->fullSData(oldp+393,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[11]),16);
    bufp->fullSData(oldp+394,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[12]),16);
    bufp->fullSData(oldp+395,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[13]),16);
    bufp->fullSData(oldp+396,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[14]),16);
    bufp->fullSData(oldp+397,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[15]),16);
    bufp->fullSData(oldp+398,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[16]),16);
    bufp->fullSData(oldp+399,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[17]),16);
    bufp->fullSData(oldp+400,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[18]),16);
    bufp->fullSData(oldp+401,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[19]),16);
    bufp->fullSData(oldp+402,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[20]),16);
    bufp->fullSData(oldp+403,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[21]),16);
    bufp->fullSData(oldp+404,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[22]),16);
    bufp->fullSData(oldp+405,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[23]),16);
    bufp->fullSData(oldp+406,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[24]),16);
    bufp->fullSData(oldp+407,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[25]),16);
    bufp->fullSData(oldp+408,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[26]),16);
    bufp->fullSData(oldp+409,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[27]),16);
    bufp->fullSData(oldp+410,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[28]),16);
    bufp->fullSData(oldp+411,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[29]),16);
    bufp->fullSData(oldp+412,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[30]),16);
    bufp->fullSData(oldp+413,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr[31]),16);
    bufp->fullSData(oldp+414,((0x000003ffU & ((IData)(vlSelfRef.single_block_bench__DOT__DUT__DOT__done_rows)
                                               ? (IData)(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_write_counter)
                                               : VL_SHIFTL_III(32,32,32, (IData)(vlSelfRef.single_block_bench__DOT__DUT__DOT__arr_write_counter), 5U)))),10);
    bufp->fullIData(oldp+415,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__j),32);
    bufp->fullSData(oldp+416,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[0]),16);
    bufp->fullSData(oldp+417,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[1]),16);
    bufp->fullSData(oldp+418,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[2]),16);
    bufp->fullSData(oldp+419,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[3]),16);
    bufp->fullSData(oldp+420,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[4]),16);
    bufp->fullSData(oldp+421,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[5]),16);
    bufp->fullSData(oldp+422,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[6]),16);
    bufp->fullSData(oldp+423,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[7]),16);
    bufp->fullSData(oldp+424,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[8]),16);
    bufp->fullSData(oldp+425,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[9]),16);
    bufp->fullSData(oldp+426,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[10]),16);
    bufp->fullSData(oldp+427,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[11]),16);
    bufp->fullSData(oldp+428,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[12]),16);
    bufp->fullSData(oldp+429,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[13]),16);
    bufp->fullSData(oldp+430,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[14]),16);
    bufp->fullSData(oldp+431,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[15]),16);
    bufp->fullSData(oldp+432,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[16]),16);
    bufp->fullSData(oldp+433,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[17]),16);
    bufp->fullSData(oldp+434,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[18]),16);
    bufp->fullSData(oldp+435,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[19]),16);
    bufp->fullSData(oldp+436,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[20]),16);
    bufp->fullSData(oldp+437,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[21]),16);
    bufp->fullSData(oldp+438,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[22]),16);
    bufp->fullSData(oldp+439,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[23]),16);
    bufp->fullSData(oldp+440,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[24]),16);
    bufp->fullSData(oldp+441,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[25]),16);
    bufp->fullSData(oldp+442,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[26]),16);
    bufp->fullSData(oldp+443,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[27]),16);
    bufp->fullSData(oldp+444,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[28]),16);
    bufp->fullSData(oldp+445,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[29]),16);
    bufp->fullSData(oldp+446,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[30]),16);
    bufp->fullSData(oldp+447,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__arr_internal[31]),16);
    bufp->fullIData(oldp+448,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__state_mem_write),32);
    bufp->fullCData(oldp+449,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__mem_write_counter),5);
    bufp->fullBit(oldp+450,(vlSelfRef.single_block_bench__DOT__DUT__DOT__writer__DOT__try_get_lock));
    bufp->fullIData(oldp+451,(vlSelfRef.single_block_bench__DOT__TESTMEM_16_1024__DOT__i),32);
    bufp->fullBit(oldp+452,(vlSelfRef.single_block_bench__DOT__clk));
    bufp->fullBit(oldp+453,(vlSelfRef.single_block_bench__DOT__rst));
    bufp->fullBit(oldp+454,(vlSelfRef.single_block_bench__DOT__DUT__DOT____Vcellinp__inv_dct__rst));
}
